// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Displays the home page",
                "tags": [
                    "Admin"
                ],
                "summary": "Home Page",
                "responses": {}
            },
            "post": {
                "description": "Displays the home page",
                "tags": [
                    "Admin"
                ],
                "summary": "Home Page",
                "responses": {}
            }
        },
        "/admin/customers": {
            "get": {
                "description": "Fetches the customers",
                "tags": [
                    "Admin"
                ],
                "summary": "Fetch Customers",
                "responses": {}
            }
        },
        "/admin/logout": {
            "get": {
                "description": "Logs out the user",
                "tags": [
                    "Admin"
                ],
                "summary": "Logout",
                "responses": {}
            }
        },
        "/admin/main": {
            "get": {
                "description": "Displays the main page",
                "tags": [
                    "Admin"
                ],
                "summary": "Main Page",
                "responses": {}
            }
        },
        "/admin/savecustomer": {
            "get": {
                "description": "Saves a customer",
                "tags": [
                    "Admin"
                ],
                "summary": "Save Customer",
                "responses": {}
            },
            "post": {
                "description": "Saves a customer",
                "tags": [
                    "Admin"
                ],
                "summary": "Save Customer",
                "responses": {}
            }
        },
        "/admin/success": {
            "get": {
                "description": "Displays the success page",
                "tags": [
                    "Admin"
                ],
                "summary": "Success Page",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Erply Test Task",
	Description:      "This is a test task for Erply using Erply API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
